### ISSUE TITLE
Installation fails on SparkyCI 

### ISSUE THREAD

**Issue by melezhik** [antononcube/Raku-Data-Reshapers#1]
Hi!

Installation fails, with such an error:

```
Install Raku dependencies with: zef install --deps-only --test-depends --/test .
13:54:25 05/05/2022 [repository] :: installing bash, version 0.002001
13:54:35 05/05/2022 [bash: install deps] :: ===> Searching for missing dependencies: Text::CSV, Pretty::Table
13:54:35 05/05/2022 [bash: install deps] :: ===> Updating fez mirror: https://360.zef.pm/
13:55:24 05/05/2022 [bash: install deps] :: ===> Searching for missing dependencies: Slang::Tuxic, File::Temp, Text::Wrap
13:55:24 05/05/2022 [bash: install deps] :: ===> Installing: Slang::Tuxic:ver<0.0.1>
13:55:24 05/05/2022 [bash: install deps] :: ===> Installing: File::Temp:ver<0.0.10>:auth
13:55:24 05/05/2022 [bash: install deps] :: ===> Installing: Text::CSV:ver<0.010>:auth
13:55:24 05/05/2022 [bash: install deps] :: ===> Installing: _:ver<0.0.1>:auth
13:55:24 05/05/2022 [bash: install deps] :: ===> Installing: Pretty::Table:ver<0.0.2>:auth
13:55:24 05/05/2022 [bash: install deps] :: ===> Install [FAIL] for Pretty::Table:ver<0.0.2>:auth: [31m===[0mSORRY![31m===[0m Error while compiling /home/raku/.sparky/projects/raku/.sparrowdo/scm/home#sources/3D8D3D2548BB69EE2C8D1CA7603C838CFAA227E6 (Pretty::Table)
13:55:24 05/05/2022 [bash: install deps] :: Undeclared routine:
13:55:24 05/05/2022 [bash: install deps] ::     wrap-text used at line 1049
13:55:24 05/05/2022 [bash: install deps] :: 
```

Full report - http://sparrowhub.io:2222/report/386

cc @uzluisf

HTH

Aleksei

**Comment by melezhik** [comment]
Looks like Pretty::Table issue - http://sparrowhub.io:2222/report/388

**Comment by antononcube** [comment]
@melezhik  Thank you for bringing this issue to my attention! 

It seems to me that `Pretty::Table` is "abandoned." (I install it from GitLab, not from PAUSE / raku.land.)

What is the best way to address those issues?

- I can replace `Pretty::Table` in `Data::Reshapers` with a more maintained package.
- I can duplicate the tabulation functionalities in some way in `Data::Reshapers`.
- Someone has to re-own `Pretty::Table`.
   - I am willing to do it, but I am not sure how...

**Comment by melezhik** [comment]
@antononcube I'd ask in Raku IRC

**Comment by melezhik** [comment]
Should bump a version of Pretty::Table as well? - it still fails - http://sparrowhub.io:2222/report/531

**Comment by antononcube** [comment]
I bumped the version. But apparently I fixed another bug (about slicing method) not the `wrap-text` related one.
Currently, for some reason an old version of "Text::Wrap" is picked.

**Comment by melezhik** [comment]
So, it not yet fixed, yeah?

here is the report for your repo - http://sparrowhub.io:2222/report/532

**Comment by antononcube** [comment]
I fixed the "Pretty::Table" issues. 

Now I get failures in one of these test files:  http://sparrowhub.io:2222/report/706 .

But I do not get these failures when I install that package locally (macOS) or on a certain remote Linux (Ubuntu) machine. What would be the reason? Is there something I can investigate / debug further? (I think I need your help... :) )

**Comment by melezhik** [comment]
Please enable verbose mode in .sparkyci.yaml and run again - https://github.com/melezhik/sparkyci/blob/main/docs/dsl.md

**Comment by melezhik** [comment]
yeah, underlying sparkyci worker hung, so I restarted it and new build should come up

**Comment by melezhik** [comment]
The last build shows a cause of the issue - sparrowhub.io:2222/report/763

**Comment by antononcube** [comment]
Yeah, I saw the errors:

```shell
21:39:10 06/27/2022 [bash: run tests] :: # Failed test 'join across inner'
21:39:10 06/27/2022 [bash: run tests] :: # at t/08-join-across.rakutest line 61
21:39:10 06/27/2022 [bash: run tests] :: # expected: $(${:A("a"), :B("n"), :C(5), :D("i"), :E(13)}, ${:A("l"), :B("n"), :C(3), :D("i"), :E(13)})
21:39:10 06/27/2022 [bash: run tests] :: #      got: $(${:A("a"), :B("n"), :C(5), :D("i"), :E(13)}, ${:A("a"), :B("n"), :C(5), :D("i"), :E(13)})
21:39:10 06/27/2022 [bash: run tests] :: Cannot modify an immutable Nil value
21:39:10 06/27/2022 [bash: run tests] ::   in block  at /home/raku/.raku/sources/F7993C3B2856EABC58CC7CF9EADCA6DDB4F03527 (Hash::Merge) line 53
21:39:10 06/27/2022 [bash: run tests] ::   in sub merge-hash at /home/raku/.raku/sources/F7993C3B2856EABC58CC7CF9EADCA6DDB4F03527 (Hash::Merge) line 57
21:39:10 06/27/2022 [bash: run tests] ::   in sub JoinAcross at /home/raku/.sparky/projects/raku/.sparrowdo/scm/lib/Data/Reshapers/JoinAcross.rakumod (Data::Reshapers::JoinAcross) line 93
21:39:10 06/27/2022 [bash: run tests] ::   in sub JoinAcross at /home/raku/.sparky/projects/raku/.sparrowdo/scm/lib/Data/Reshapers/JoinAcross.rakumod (Data::Reshapers::JoinAcross) line 44
21:39:10 06/27/2022 [bash: run tests] ::   in sub JoinAcross at /home/raku/.sparky/projects/raku/.sparrowdo/scm/lib/Data/Reshapers/JoinAcross.rakumod (Data::Reshapers::JoinAcross) line 25
21:39:10 06/27/2022 [bash: run tests] ::   in sub join-across at /home/raku/.sparky/projects/raku/.sparrowdo/scm/lib/Data/Reshapers.rakumod (Data::Reshapers) line 94
21:39:10 06/27/2022 [bash: run tests] ::   in block <unit> at t/08-join-across.rakutest line 62
21:39:10 06/27/2022 [bash: run tests] :: 
```

Those errors do not happen on my machine (macOS).
On what platform SparkyCI executes the tests?

**Comment by melezhik** [comment]
On alpine Linux, also please see Rakudo version in a init tab, could be a rakudo specific bug 🤔

**Comment by antononcube** [comment]
Well, it looks ok now: http://sparrowhub.io:2222/report/766 .

I made two changes:

- Change the reduce statement to use `!:deep`.

- Put more detailed dependency on "Hash::Merge" (version and api)

**Comment by melezhik** [comment]
Good!

**Comment by antononcube** [comment]
@melezhik  Thank you for your efforts on SparkyCI, and thank you for bringing my attention to this issue!
